### PRODUCTS INDEX
GET http://localhost:3000/products.json

### PRODUCTS CREATE
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Test name",
  "price": 32,
  "description": "test description"
}

### PRODUCTS SHOW
GET http://localhost:3000/products/1.json

### PRODUCTS UPDATE
PATCH http://localhost:3000/products/11.json
Content-Type: application/json

{
  "price": 100
}

### PRODUCTS DESTROY
DELETE http://localhost:3000/products/11.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Scout",
  "email": "scout@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "amanda@example.com",
  "password": "password"
}

### Orders create 
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc4MjIxMjJ9.-AiAKTq8dMyt6GV8Ff4SBrD5I9BG67fUJEQVj7fk028
Content-Type: application/json

{
  "product_id": 2, 
  "quantity": 2,
}